### PR TITLE
feat(css): add styling to audio tags for Chromium browsers

### PR DESCRIPTION
**Pull request by AceLikesGhosts**
| boob                   |
|-------------------|
| This PR ➕ some basic 💅 to `🔉` elements for "chromium

### CODE REVIEW

**Comment by l1mey112** [comment]
i am in debt to you, CSS is a pain.

**Review by l1mey112 — APPROVED** [review]
good work. i'll fix up the colours in a later PR.

**Comment by AceLikesGhosts** [comment]
IM BETTER
"youre dumb"

**Comment by AceLikesGhosts** [comment]
> good work. i'll fix up the colours in a later PR.

he in fact, did not, and did not deploy it to prod :(

**Pull request merged**
